framework:
  messenger:
    transports:
      # Transport asynchrone : Redis (défini en .env.local -> MESSENGER_TRANSPORT_DSN="${REDIS_URL}/messages")
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 3
          delay: 1000
          multiplier: 2

    routing:
      # Route tous les messages applicatifs vers 'async'.
      # Tu peux remplacer par des classes précises si nécessaire (ex: App\Message\SendMail).
      'App\Message\*': async
