monolog:
    channels: [deprecation, security]  # on déclare aussi "security"

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.project_dir%/var/log/app_dev.json'
                level: debug
                formatter: monolog.formatter.json
                channels: ['!security']   # on exclut le channel security du main
            console:
                type: console
                process_psr_3_messages: false
                channels: ['!event', '!doctrine', '!console']

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ['!event']
            nested:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
            deprecations:
                type: stream
                path: "%kernel.logs_dir%/test.deprecations.log"
                level: info
                channels: [deprecation]

when@prod:
    monolog:
        handlers:
            security:
                type: stream
                path: 'php://stderr'
                level: info
                formatter: monolog.formatter.json
                channels: ['security']
            main:
                type: stream
                path: 'php://stderr'
                level: info
                formatter: monolog.formatter.json
                channels: ['!security']
            console:
                type: console
                process_psr_3_messages: false
                channels: ['!event', '!doctrine']
            deprecation:
                type: stream
                channels: [deprecation]
                path: 'php://stderr'
                formatter: monolog.formatter.json
