# config/packages/nelmio_cors.yaml
nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin:
      - 'http://localhost:3000'
      - 'http://127.0.0.1:3000'
      - 'http://localhost:5173'
      - 'http://127.0.0.1:5173'
    allow_credentials: false   # true seulement si tu utilises des cookies
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/': ~
