security:
  firewalls:
    dev:
      pattern: ^/(?:_(?:profiler|wdt)|assets/(?:css|images|js))/
      security: false

    main:
      stateless: true
      entry_point: App\Security\JsonUnauthorizedEntryPoint
      login_throttling:
        max_attempts: 5
        interval: '1 minute'
      custom_authenticators:
        - App\Security\TokenAuthenticator 

  access_control:
    # 1) Préflight CORS / OPTIONS = public (ne doit JAMAIS renvoyer 401)
    - { path: ^/,       roles: PUBLIC_ACCESS, methods: [OPTIONS] }
    # 2) Liveness/Readiness = public
    - { path: ^/healthz$, roles: PUBLIC_ACCESS }
    # 3) API v1 = authentification requise
    - { path: ^/v1,     roles: IS_AUTHENTICATED_FULLY }
