security:
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      stateless: true
      entry_point: App\Security\JsonUnauthorizedEntryPoint

  access_control:
    - { path: ^/healthz$, roles: PUBLIC_ACCESS }
    - { path: ^/v1,       roles: IS_AUTHENTICATED_FULLY }
