security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(?:_(?:profiler|wdt)|assets/(?:css|images|js))/
      security: false

    main:
      stateless: true
      provider: app_user_provider
      entry_point: App\Security\JsonUnauthorizedEntryPoint
      login_throttling:
        max_attempts: 5
        interval: '1 minute'
      custom_authenticators:
        - App\Security\TestTokenAuthenticator
        - App\Security\TokenAuthenticator

  access_control:
    # 0) CORS preflight must never be blocked
    - { path: ^/, roles: PUBLIC_ACCESS, methods: [OPTIONS] }

    # 1) Public auth endpoints (POST)
    - { path: ^/v1/auth/register$, roles: PUBLIC_ACCESS, methods: [POST] }
    - { path: ^/v1/auth/login$,    roles: PUBLIC_ACCESS, methods: [POST] }
    - { path: ^/v1/auth/logout$,   roles: PUBLIC_ACCESS, methods: [POST] }

    # 2) Public read-only endpoints (GET)
    - { path: ^/v1/artisans,   roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/v1/categories$, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/v1/categories/, roles: PUBLIC_ACCESS, methods: [GET] } # for future /v1/categories/<slug>
    - { path: ^/v1/services$,   roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/v1/services/,   roles: PUBLIC_ACCESS, methods: [GET] }

    # 3) Health endpoints (public)
    - { path: ^/healthz$, roles: PUBLIC_ACCESS }

    # 4) Default: everything under /v1 requires auth
    - { path: ^/v1, roles: IS_AUTHENTICATED_FULLY }
