services:
  db:
    image: postgres:16-alpine
    container_name: dartech_db
    env_file: .env.docker
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dartech_net

  redis:
    image: redis:7-alpine
    container_name: dartech_redis
    command: ["redis-server","--appendonly","yes"]
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dartech_net

volumes:
  pg_data:
  redis_data:

networks:
  dartech_net:
