monolog:
  handlers:
    main:
      type: stream
      path: '%kernel.project_dir%/var/log/app_dev.json'
      level: debug
      formatter: monolog.formatter.json
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine", "!console" ]
