name: CI
on:
  pull_request:
    branches: ["main"]

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: composer:v2   # pas de 'cache:' ici
      - name: Validate composer.json
        run: composer validate --no-check-all --no-check-publish
